### HWK 4

#### Name: Raphael Ossa
#### UT EID: rso388

#### Name:
#### UT EID:

#### Date:

##### Task 0: Import Libraries and Read Data

In [1]:
# import libraries
import pandas as pd
import seaborn as sns

In [2]:
# read the data file and create a Pandas dataframe
df = pd.read_csv('Life_Expectancy_Data.csv')

##### Task 1: Get Simple Statistics of the Dataset

**Q1a (2 points).** Get the size of the dataframe and simple statistics of the dataset like - count, max, min, std, mean

**Q1b (2 points).** Get the first 8 rows of the dataset

**Q1c (2 points).** Get the last 6 rows of the dataset

**Q1d (2 points).** Get the columns of the dataset and their types

##### TASK 2: Work with Missing Data

**Q2a (4 points).** Locate rows that have Null values by running df.isnull()

**Q2b (4 points).** Find the total number of missing elements per column

**Q2c (4 points).** Make a heatmap of the missing values using plotly (https://plotly.com/python-api-reference/generated/plotly.express.imshow.html). Make sure to add labels for the x and y axis.

In [ ]:
import plotly.express as px

# graph the heatmap
# fig = 

# label the axes appropriately

# hide the color axes (given to you below)
# fig.update_coloraxes(showscale=False)

# show the graph

**Q2d (4 points).** Pick two columns in the dataset which have correlating missing values (i.e. values which are missing in the same row for different columns). Why do you think correlated missing values occurred for these columns in particular?

**Q2e (4 points).** Wellness can be defined in practical terms as a holistic integration of physical, mental, and spiritual well-being. Let's say you're trying to make predictions of the wellness of a person in this dataset who has some missing datapoints. Do you think the missing values in this dataset affect the quality of your wellness predictions? Why or why not?

**Q2f (4 points).** Drop any row that contains a Null value. Reset the index after the drop.

Dropping any row that has a single missing value is extreme. Let us say that we were going to study the relationship between 'Life expectancy' and 'GDP' and 'Schooling'. Our expectation is that there will be a higher life expectancy with higher GDP and higher schooling.

In [ ]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

**Q2g (4 points).** Drop rows that have missing 'Life expectancy', 'GDP', and 'Schooling'. These data are essential to our study.

**Q2h (4 points).** Check that there are no missing values for the columns 'Life expectancy', 'GDP', and 'Schooling'.

An alternative to dropping the missing values would be to replace the missing values with the median for that column since the median is not that sensitive to outliers.

In [ ]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

**Q2h (4 points).** Replace the missing values in columns 'Life expectancy', 'GDP', and 'Schooling' with the median values for these columns

**Q2i (4 points).** Check that the replacements took place

##### Task 3: One-Hot Encoding
One-Hot Encoding is a process of transforming categorical data into numerical data. Research how this is done in Pandas.

In [ ]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

The column 'Status' has categorical data. That data classifies countries as either 'Developing' or 'Developed'.

In [ ]:
# check the actual categorical values used
df['Status'].unique()

In [ ]:
# research the function get_dummies()
Status_Encoded = pd.get_dummies(df['Status'])
print(Status_Encoded)

**Q3a (4 points).** If the output of the previous cell shows 'True' and 'False' values, convert them to 1 and 0 respectively. Add the two columns 'Developed' and 'Developing' (which should have values of 1s or 0s) after 'Status.' Check that the columns were added correctly.

**Q3b (4 points).** Print the number of 'Developed' and 'Developing' countries

**Q3c (4 points).** Print the mean 'Life expectancy' of 'Developed' countries and the the mean 'Life expectancy' of 'Developing' countries

##### Task 4: Normalize Data

Normalization is peformed to have data values in the range from 0 to 1.

x_normal = (x_raw - x_min) / (x_max - x_min)

Use MinMaxScaler in scikit-learn to perform the transformation

In [6]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

In [7]:
# show the values
df['Life expectancy'].values

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ], shape=(2938,))

In [8]:
# normalization makes the transformed values range from 0 to 1
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['Life expectancy'] = scaler.fit_transform(df['Life expectancy'].values.reshape(-1,1))

In [9]:
# show the values
df['Life expectancy']

0       0.544592
1       0.447818
2       0.447818
3       0.440228
4       0.434535
          ...
2933    0.151803
2934    0.155598
2935    0.161290
2936    0.170778
2937    0.184061
Name: Life expectancy, Length: 2938, dtype: float64

In [10]:
# redo the statistics
df['Life expectancy'].describe()

count    2928.000000
mean        0.624762
std         0.180719
min         0.000000
25%         0.508539
50%         0.679317
75%         0.747628
max         1.000000
Name: Life expectancy, dtype: float64

In [11]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

**Q4a (5 points).** Normalize the data for 'Life expectancy', 'GDP', and 'Schooling' instead of over-writing the raw values create three columns: 'life_expectancy_normal', 'gdp_normal', and 'schooling_normal' and fill them with normalized data

In [12]:
scaler = MinMaxScaler()
df['life_expectancy_normal'] = scaler.fit_transform(df['Life expectancy'].values.reshape(-1,1))
df['gdp_normal'] = scaler.fit_transform(df['GDP'].values.reshape(-1,1))
df['schooling_normal'] = scaler.fit_transform(df['Schooling'].values.reshape(-1,1))

**Q4b (5 points).** Check that these three columns were created with normalized data

In [16]:
df[["life_expectancy_normal", "gdp_normal", "schooling_normal"]]

      life_expectancy_normal  gdp_normal  schooling_normal
0                   0.544592    0.004889          0.487923
1                   0.447818    0.005127          0.483092
2                   0.447818    0.005287          0.478261
3                   0.440228    0.005608          0.473430
4                   0.434535    0.000519          0.458937
...                      ...         ...               ...
2933                0.151803    0.003799          0.444444
2934                0.155598    0.003790          0.458937
2935                0.161290    0.000467          0.483092
2936                0.170778    0.004589          0.473430
2937                0.184061    0.004579          0.473430

[2938 rows x 3 columns]

##### Task 5: Perform Standardization

Standardization is performed to transform data to have a mean of zero  
and standard deviation of 1.

The standardized value is also called the z-score.

x_z = (x_raw - x_mean) / x_std

Use StandardScaler in scikit-learn to perform the standardization.

In [17]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

In [18]:
# get the life expectancy values
df['Life expectancy'].values

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ], shape=(2938,))

In [19]:
# Standardization transforms values to have a mean of 0 and standard
# deviation of 1
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['Life expectancy'] = scaler.fit_transform(df['Life expectancy'].values.reshape(-1,1))

In [20]:
# check the standardized values
df['Life expectancy']

0      -0.443691
1      -0.979279
2      -0.979279
3      -1.021286
4      -1.052791
          ...
2933   -2.617549
2934   -2.596545
2935   -2.565040
2936   -2.512532
2937   -2.439020
Name: Life expectancy, Length: 2938, dtype: float64

In [21]:
# run simple statistics on that column
df['Life expectancy'].describe()

count    2.928000e+03
mean    -6.891876e-16
std      1.000171e+00
min     -3.457687e+00
25%     -6.432238e-01
50%      3.019319e-01
75%      6.799942e-01
max      2.076724e+00
Name: Life expectancy, dtype: float64

In [22]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

**Q5a (5 points).** Standardize the data for 'Life expectancy', 'GDP', and 'Schooling' instead of over-writing the raw values create three columns: 'life_expectancy_z', 'gdp_z', and 'schooling_z' and fill them with standardized data

In [23]:
df['life_expectancy_z'] = scaler.fit_transform(df['Life expectancy'].values.reshape(-1,1))
df['gdp_z'] = scaler.fit_transform(df['GDP'].values.reshape(-1,1))
df['schooling_z'] = scaler.fit_transform(df['Schooling'].values.reshape(-1,1))

**Q5b (5 points).** Check that these three columns were created with standardized data

In [24]:
df[["life_expectancy_z", "gdp_z", "schooling_z"]]

      life_expectancy_z     gdp_z  schooling_z
0             -0.443691 -0.483546    -0.563614
1             -0.979279 -0.481553    -0.593391
2             -0.979279 -0.480218    -0.623168
3             -1.021286 -0.477539    -0.652944
4             -1.052791 -0.520044    -0.742275
...                 ...       ...          ...
2933          -2.617549 -0.492650    -0.831606
2934          -2.596545 -0.492722    -0.742275
2935          -2.565040 -0.520477    -0.593391
2936          -2.512532 -0.486046    -0.652944
2937          -2.439020 -0.486132    -0.652944

[2938 rows x 3 columns]

##### Task 6: Applying Custom Function to Transform Data

In [25]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')

In [26]:
# asuume that percentage expenditure has increased by 5%
# define a function that increases all elements by a fixed value of 5% (for simplicity sake) 
def percentage_expenditure_update(balance):
    return balance + 5

In [ ]:
# apply that function to the DataFrame 
df['percentage expenditure'] = df['percentage expenditure'].apply(percentage_expenditure_update)

**Q6a (5 points).** Check that the values in 'percentage expenditure' did change

In [37]:
# reread the raw data again
df = pd.read_csv ('Life_Expectancy_Data.csv')
print("Before", df['percentage expenditure'], sep="\n")
df['percentage expenditure'] = df['percentage expenditure'].apply(percentage_expenditure_update)
print("\nAfter", df['percentage expenditure'], sep="\n")

Before
0       71.279624
1       73.523582
2       73.219243
3       78.184215
4        7.097109
          ...
2933     0.000000
2934     0.000000
2935     0.000000
2936     0.000000
2937     0.000000
Name: percentage expenditure, Length: 2938, dtype: float64

After
0       76.279624
1       78.523582
2       78.219243
3       83.184215
4       12.097109
          ...
2933     5.000000
2934     5.000000
2935     5.000000
2936     5.000000
2937     5.000000
Name: percentage expenditure, Length: 2938, dtype: float64

**Q6b (5 points).** Create your own function to perform standardization

In [42]:
# def standardize
def standardize(value, mean, std):
    return (value - mean) / std

**Q6c (5 points).** Apply the function standardize() to the GDP values.
Store the results in a new column called z_gdp

In [44]:
mu, sigma = df['GDP'].mean(), df['GDP'].std()
df['z_gdp'] = df['GDP'].apply(standardize, mean=mu, std=sigma)

**Q6d (5 points).** Compare your standardized values with those obtained from scikit-learn

In [45]:
scaler = StandardScaler()
df['gdp_z'] = scaler.fit_transform(df['GDP'].values.reshape(-1,1))
df[["z_gdp", "gdp_z"]]

         z_gdp     gdp_z
0    -0.483449 -0.483546
1    -0.481456 -0.481553
2    -0.480121 -0.480218
3    -0.477443 -0.477539
4    -0.519939 -0.520044
...        ...       ...
2933 -0.492551 -0.492650
2934 -0.492623 -0.492722
2935 -0.520373 -0.520477
2936 -0.485949 -0.486046
2937 -0.486035 -0.486132

[2938 rows x 2 columns]